# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
cache: packages

script:
  - |
    R CMD build .
    travis_wait 60 R CMD check splinetree*tar.gz
